name: Build LaTeX Document

on:
  push

jobs:
  build_paper:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: haozhu10015/.github/actions/latex@main
        with:
          # space-separated list of LaTeX files to compile
          paper: article/article.tex slides_original/slides_original.tex